FROM python
RUN sudo apt install python3-venv -y
WORKDIR /app
RUN python3 -m venv venv
RUN source venv/bin/activate
RUN pip install Flask -y
RUN python -m flask --version
RUN export FLASK_APP=app.py
RUN flask run
COPY . /app
RUN pip install -r requirements.txt 
ENTRYPOINT python app.py
